CREATE TABLE notes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  note_name TEXT NOT NULL,
  note_content TEXT,
  folder_id INTEGER REFERENCES folders(id) not null,
  date_created TIMESTAMPTZ NOT NULL DEFAULT now()
);